import React from 'react';

export  const SIGNUP_START = 'SIGNUP_START';
export  const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export  const SIGNUP_FAIL = 'SIGNUP_FAIL';

export  const VERIFY_START = 'VERIFY_START';
export  const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export  const VERIFY_FAIL = 'VERIFY_FAIL';

export  const CREATE_WORKSPACE_START = 'CREATE_WORKSPACE_START';
export  const CREATE_WORKSPACE_SUCCESS = 'CREATE_WORKSPACE_SUCCESS';
export  const CREATE_WORKSPACE_FAIL = 'CREATE_WORKSPACE_FAIL';

export  const DELETE_WORKSPACE_START = 'DELETE_WORKSPACE_START';
export  const DELETE_WORKSPACE_SUCCESS = 'DELETE_WORKSPACE_SUCCESS';
export  const DELETE_WORKSPACE_FAIL = 'DELETE_WORKSPACE_FAIL';

export  const GET_WORKSPACES_START = 'GET_WORKSPACES_START';
export  const GET_WORKSPACES_SUCCESS = 'GET_WORKSPACES_SUCCESS';
export  const GET_WORKSPACES_FAIL = 'GET_WORKSPACES_FAIL';

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const DEFAULT_ERROR_MESSAGE = 'Something went wrong. Please try again later.';
export const SERVER_ERROR = 'SERVER_ERROR';
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

export  const RESET_VALIDATIONS_ERRORS = 'RESET_VALIDATIONS_ERRORS';
export  const RESET_SERVER_ERROR = 'RESET_SERVER_ERROR';
export  const RESET_AUTHORIZATION_ERROR = 'RESET_AUTHORIZATION_ERROR';

export const RESET_UNKNOWN_ERROR = 'RESET_UNKNOWN_ERROR';
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR'

export  const AUTH_LOGOUT = 'AUTH_LOGOUT';
